# Generated by Django 5.1.7 on 2025-03-10 11:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emploidutemps',
            name='creneaux',
        ),
        migrations.AlterModelOptions(
            name='classe',
            options={'verbose_name': 'Classe', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='filiere',
            options={'verbose_name': 'Filière', 'verbose_name_plural': 'Filières'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date_envoi']},
        ),
        migrations.AlterModelOptions(
            name='structureacademique',
            options={'verbose_name': 'Structure Académique', 'verbose_name_plural': 'Structures Académiques'},
        ),
        migrations.RemoveField(
            model_name='classe',
            name='enseignant',
        ),
        migrations.RemoveField(
            model_name='message',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='structureacademique',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='structureacademique',
            name='filieres',
        ),
        migrations.AddField(
            model_name='classe',
            name='enseignants',
            field=models.ManyToManyField(blank=True, related_name='classes_enseignees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='classe',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='School.structureacademique'),
        ),
        migrations.AddField(
            model_name='cours',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cours',
            name='etudiants',
            field=models.ManyToManyField(blank=True, related_name='cours_suivis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cours',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='discussion',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='filiere',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='filiere',
            name='structure',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filieres', to='School.structureacademique'),
        ),
        migrations.AddField(
            model_name='forum',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='materiel',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='message',
            name='date_envoi',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='message',
            name='expediteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='structureacademique',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='structureacademique',
            name='nom',
            field=models.CharField(default='Structure Principale', max_length=200),
        ),
        migrations.AlterField(
            model_name='classe',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='School.filiere'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cours',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='cours',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_enseignes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cours',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cours',
            name='materiels',
            field=models.ManyToManyField(blank=True, related_name='cours', to='School.materiel'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='discussion', to='School.message'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='discussions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emploidutemps',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='forum',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='forum',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='forum', to='School.message'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='contenu',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='type',
            field=models.CharField(default='document', max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='reponses',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='cours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='School.cours'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='quiz', to='School.question'),
        ),
        migrations.AlterField(
            model_name='structureacademique',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('TEACHER', 'Enseignant'), ('STUDENT', 'Étudiant'), ('ACADEMIC', 'Responsable Académique')], default='STUDENT', max_length=10),
        ),
        migrations.DeleteModel(
            name='Creneau',
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='creneaux',
            field=models.JSONField(default=dict),
        ),
    ]
