# Generated by Django 5.1.7 on 2025-03-10 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0004_remove_emploidutemps_creneaux_alter_classe_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultatQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('date_completion', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_quiz', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='School.quiz')),
            ],
            options={
                'verbose_name': 'Résultat de quiz',
                'verbose_name_plural': 'Résultats de quiz',
                'unique_together': {('quiz', 'etudiant')},
            },
        ),
    ]
