# Generated by Django 5.1.7 on 2025-03-17 03:26

import datetime
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0005_resultatquiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classe',
            options={'verbose_name': 'classe', 'verbose_name_plural': 'classes'},
        ),
        migrations.AlterModelOptions(
            name='cours',
            options={'verbose_name': 'cours', 'verbose_name_plural': 'cours'},
        ),
        migrations.AlterModelOptions(
            name='discussion',
            options={'verbose_name': 'discussion', 'verbose_name_plural': 'discussions'},
        ),
        migrations.AlterModelOptions(
            name='emploidutemps',
            options={'verbose_name': 'emploi du temps', 'verbose_name_plural': 'emplois du temps'},
        ),
        migrations.AlterModelOptions(
            name='filiere',
            options={'verbose_name': 'filière', 'verbose_name_plural': 'filières'},
        ),
        migrations.AlterModelOptions(
            name='materiel',
            options={'verbose_name': 'matériel', 'verbose_name_plural': 'matériels'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date_envoi'], 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'question', 'verbose_name_plural': 'questions'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'quiz', 'verbose_name_plural': 'quiz'},
        ),
        migrations.AlterModelOptions(
            name='resultatquiz',
            options={'verbose_name': 'résultat de quiz', 'verbose_name_plural': 'résultats de quiz'},
        ),
        migrations.AlterModelOptions(
            name='structureacademique',
            options={'verbose_name': 'structure académique', 'verbose_name_plural': 'structures académiques'},
        ),
        migrations.AddField(
            model_name='classe',
            name='annee_scolaire',
            field=models.CharField(default='2025-2026', max_length=9),
        ),
        migrations.AddField(
            model_name='classe',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Description de la classe'),
        ),
        migrations.AddField(
            model_name='cours',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='School.classe'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussions_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussion',
            name='contenu',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Contenu de la discussion'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussions', to='School.forum'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discussion',
            name='titre',
            field=models.CharField(default='Nouvelle discussion', max_length=200),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplois_du_temps', to='School.classe'),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='cours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creneaux', to='School.cours'),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='heure_debut',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='heure_fin',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='jour',
            field=models.CharField(default='Lundi', max_length=10),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='salle',
            field=models.CharField(default='Salle non assignée', max_length=50),
        ),
        migrations.AddField(
            model_name='filiere',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filieres_gerees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forum',
            name='cours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forums', to='School.cours'),
        ),
        migrations.AddField(
            model_name='forum',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Description du forum'),
        ),
        migrations.AddField(
            model_name='forum',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='materiel',
            name='cours_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiels_cours', to='School.cours'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Description du matériel'),
        ),
        migrations.AddField(
            model_name='message',
            name='discussion_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_discussion', to='School.discussion'),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_quiz', to='School.quiz'),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('QCM', 'Choix multiple'), ('LIBRE', 'Réponse libre'), ('VF', 'Vrai/Faux')], default='QCM', max_length=5),
        ),
        migrations.AddField(
            model_name='quiz',
            name='date_limite',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Description du quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='duree',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resultatquiz',
            name='date_soumission',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='resultatquiz',
            name='reponses',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='structureacademique',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Description de la structure académique'),
        ),
        migrations.AddField(
            model_name='structureacademique',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structures_gerees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_inscription',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='classe',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='School.filiere'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='nom',
            field=models.CharField(default='Nouvelle classe', max_length=100),
        ),
        migrations.AlterField(
            model_name='classe',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='School.structureacademique'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cours',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Description du cours'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='enseignant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours_enseignes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cours',
            name='materiels',
            field=models.ManyToManyField(blank=True, related_name='cours_associes', to='School.materiel'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='titre',
            field=models.CharField(default='Nouveau cours', max_length=200),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='discussions_associees', to='School.message'),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Description de la filière'),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='nom',
            field=models.CharField(default='Nouvelle filière', max_length=100),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filieres', to='School.structureacademique'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='titre',
            field=models.CharField(default='Nouveau forum', max_length=200),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='contenu',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Contenu du matériel'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='titre',
            field=models.CharField(default='Nouveau matériel', max_length=200),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='type',
            field=models.CharField(choices=[('PDF', 'Document PDF'), ('VIDEO', 'Vidéo'), ('AUDIO', 'Audio'), ('AUTRE', 'Autre')], default='AUTRE', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='contenu',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Nouveau message'),
        ),
        migrations.AlterField(
            model_name='question',
            name='reponse_correcte',
            field=models.TextField(default='Option 1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='reponses',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Option 1;Option 2;Option 3', help_text='Pour les QCM, séparez les réponses par des points-virgules'),
        ),
        migrations.AlterField(
            model_name='question',
            name='texte',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Question'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='cours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz', to='School.cours'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='quiz_associes', to='School.question'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='titre',
            field=models.CharField(default='Nouveau quiz', max_length=200),
        ),
        migrations.AlterField(
            model_name='resultatquiz',
            name='date_completion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='resultatquiz',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
