# Generated by Django 5.1.7 on 2025-03-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0008_alter_utilisateur_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
