# Generated by Django 5.1.7 on 2025-03-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0009_alter_utilisateur_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cours/images/'),
        ),
        migrations.AddField(
            model_name='cours',
            name='video_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
